export const AUTH = {
    REGISTER: {
        SUCCESS: "RSUCCESS",
        FAILURE: "RFAILURE"
    },
    LOGIN: {
        SUCCESS: "LSUCCESS",
        FAILURE: "LFAILURE"
    },
    LOGOUT: "LOGOUT",
    CLEAR_ERROR: "CLEAR_ERROR"
};

export const GET_ALL_POSTS_REQUEST= "GET_ALL_POSTS_REQUEST";
export const GET_ALL_POSTS_SUCCESS= "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_FAILURE= "GET_ALL_POSTS_FAILURE"

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';

export const UPDATE_COMMENT_REQUEST = 'UPDATE_COMMENT_REQUEST';
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const UPDATE_COMMENT_FAILURE = 'UPDATE_COMMENT_FAILURE';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';
